### ISSUE TITLE
Trying to Run the Glitch Project: Uncaught (in promise) Error

### ISSUE THREAD

**Issue by MarthB** [akbartus/MobileSAM-in-the-Browser#6]
I am a complete beginner with running ML models but I have been trying to run the Glitch project. Every time I upload an image it gives me two errors (see below imgae) :
1. Failed to load resource: net::ERR_CONNECTION_RESET

2. Uncaught (in promise) TypeError: Failed to fetch
    at e.OnnxruntimeWebAssemblySessionHandler.createSessionAllocate (ort.wasm.min.js:6:76144)
    at e.OnnxruntimeWebAssemblySessionHandler.loadModel (ort.wasm.min.js:6:76704)
    at async Object.createSessionHandler (ort.wasm.min.js:6:69742)
    at async h.create (ort.wasm.min.js:6:11814)
    at async handleImage (main.js:83:21)

![Screenshot 2023-12-06 123601](https://github.com/akbartus/MobileSAM-in-the-Browser/assets/26886253/f9428cbe-34e5-45eb-a65c-509bed44b9c3)

How can I fix this?

**Comment by MarthB** [comment]
I tried both brave and chrome

**Comment by MarthB** [comment]
Another theory is that the encoder isn't loading - when I try the link on the github page and from the code both, the page cannot be reached: 
![Screenshot-2](https://github.com/akbartus/MobileSAM-in-the-Browser/assets/26886253/8c265a93-2883-4c69-b6e9-81322da0e938)
![Screenshot-1](https://github.com/akbartus/MobileSAM-in-the-Browser/assets/26886253/0bb8d6a0-a0c8-4979-b2ea-c3a5a585f8d5)
